In [173]:
import pandas as pd

In [174]:
# 原始数据路径
month = 'new'
raw_data_path = f'data/raw/巴以冲突{month}.csv'
data = pd.read_csv(raw_data_path, encoding='utf8')
data.head()

微博正文            发布时间   ip
0  【联合国机构：#本轮巴以冲突影响加沙地带超40万学生#】每经AI快讯，半岛电视台当地时间1月...  2024/1/6 23:48  NaN
1          #巴以冲突#伊朗报纸《Hamshahri》：我们将对犹太复国主义者进行最后的报复。  2024/1/6 23:33   贵州
2  朝鲜200发炮弹震惊世界，让美国很难受！这一炮表面上看起来是警告韩国，实则是警告美国。俄乌战...  2024/1/6 23:24   广东
3  巴勒斯坦“圣城旅”发布了一段有趣的加沙作战视频：他们在加沙市南部的扎伊图恩社区以南锁定了以色...  2024/1/1 23:57   陕西
4  #巴以冲突#以色列军队在约旦河西岸杰里科市入口处，用巨石砸毁了一辆巴勒斯坦人的汽车。车主此前...  2024/1/6 23:16   广东

In [175]:
import re
data.iloc[:,0] = list(map(lambda line: re.sub(r'L.*微博视频','',line), data.iloc[:,0]))
data.iloc[:,0] = list(map(lambda line: re.sub(r'#.*#','',line), data.iloc[:,0]))
data

微博正文            发布时间   ip
0     【联合国机构：】每经AI快讯，半岛电视台当地时间1月6日援引联合国人道主义事务协调厅消息称，...  2024/1/6 23:48  NaN
1                   伊朗报纸《Hamshahri》：我们将对犹太复国主义者进行最后的报复。  2024/1/6 23:33   贵州
2     朝鲜200发炮弹震惊世界，让美国很难受！这一炮表面上看起来是警告韩国，实则是警告美国。俄乌战...  2024/1/6 23:24   广东
3     巴勒斯坦“圣城旅”发布了一段有趣的加沙作战视频：他们在加沙市南部的扎伊图恩社区以南锁定了以色...  2024/1/1 23:57   陕西
4     以色列军队在约旦河西岸杰里科市入口处，用巨石砸毁了一辆巴勒斯坦人的汽车。车主此前已经被以色列...  2024/1/6 23:16   广东
...                                                 ...             ...  ...
1735  ��🇱🇱🇧据报道，黎巴嫩首都贝鲁特南郊的真主党控制区域发生了剧烈爆炸。现场发生了大火。目前还...   2024/1/3 0:32   广东
1736                                   教你不要重蹈覆辙，你还反唇相讥。   2024/1/3 0:27   云南
1737                  建个话痨群，更新一些不占用微博板面的信息消息实况互动群海岸猎人水相   2024/1/3 0:09   广西
1738  箭头社地图作者地图更新图一、塞弗尔斯克方向俄年伞兵从两侧逼近韦塞洛耶村，占领了一些据点。图二...   2024/1/3 0:07   广西
1739  以色列伞兵旅的成员伊利沙·马丁是犹太教拉比雅科夫·马丁的儿子，他的部队在加沙地区遭到巴勒斯坦...   2024/1/3 0:05   陕西

[1740 rows x 3 columns]

In [176]:
# 只保留汉字
def is_chinese(uchar):
    if uchar >= u'\u4e00' and uchar <= u'\u9fa5':
        return True
    else:
        return False

def format_str(content):
    content_str = ''
    for i in content:
        if is_chinese(i):
            content_str = content_str + i
    return content_str

data.iloc[:,0] = list(map(format_str, data.iloc[:,0]))
data

微博正文            发布时间   ip
0     联合国机构每经快讯半岛电视台当地时间月日援引联合国人道主义事务协调厅消息称本轮巴以冲突影响了...  2024/1/6 23:48  NaN
1                                伊朗报纸我们将对犹太复国主义者进行最后的报复  2024/1/6 23:33   贵州
2     朝鲜发炮弹震惊世界让美国很难受这一炮表面上看起来是警告韩国实则是警告美国俄乌战争巴以冲突胡塞...  2024/1/6 23:24   广东
3     巴勒斯坦圣城旅发布了一段有趣的加沙作战视频他们在加沙市南部的扎伊图恩社区以南锁定了以色列军队...  2024/1/1 23:57   陕西
4     以色列军队在约旦河西岸杰里科市入口处用巨石砸毁了一辆巴勒斯坦人的汽车车主此前已经被以色列当局...  2024/1/6 23:16   广东
...                                                 ...             ...  ...
1735  据报道黎巴嫩首都贝鲁特南郊的真主党控制区域发生了剧烈爆炸现场发生了大火目前还没有关于爆炸原因...   2024/1/3 0:32   广东
1736                                     教你不要重蹈覆辙你还反唇相讥   2024/1/3 0:27   云南
1737                   建个话痨群更新一些不占用微博板面的信息消息实况互动群海岸猎人水相   2024/1/3 0:09   广西
1738  箭头社地图作者地图更新图一塞弗尔斯克方向俄年伞兵从两侧逼近韦塞洛耶村占领了一些据点图二阿夫迪...   2024/1/3 0:07   广西
1739  以色列伞兵旅的成员伊利沙马丁是犹太教拉比雅科夫马丁的儿子他的部队在加沙地区遭到巴勒斯坦抵抗武...   2024/1/3 0:05   陕西

[1740 rows x 3 columns]

In [177]:
import numpy as np

# 去重
data = data.drop_duplicates(['微博正文'],keep='first')
data = data.drop(data[data['微博正文']==''].index)
data

微博正文            发布时间   ip
0     联合国机构每经快讯半岛电视台当地时间月日援引联合国人道主义事务协调厅消息称本轮巴以冲突影响了...  2024/1/6 23:48  NaN
1                                伊朗报纸我们将对犹太复国主义者进行最后的报复  2024/1/6 23:33   贵州
2     朝鲜发炮弹震惊世界让美国很难受这一炮表面上看起来是警告韩国实则是警告美国俄乌战争巴以冲突胡塞...  2024/1/6 23:24   广东
3     巴勒斯坦圣城旅发布了一段有趣的加沙作战视频他们在加沙市南部的扎伊图恩社区以南锁定了以色列军队...  2024/1/1 23:57   陕西
4     以色列军队在约旦河西岸杰里科市入口处用巨石砸毁了一辆巴勒斯坦人的汽车车主此前已经被以色列当局...  2024/1/6 23:16   广东
...                                                 ...             ...  ...
1735  据报道黎巴嫩首都贝鲁特南郊的真主党控制区域发生了剧烈爆炸现场发生了大火目前还没有关于爆炸原因...   2024/1/3 0:32   广东
1736                                     教你不要重蹈覆辙你还反唇相讥   2024/1/3 0:27   云南
1737                   建个话痨群更新一些不占用微博板面的信息消息实况互动群海岸猎人水相   2024/1/3 0:09   广西
1738  箭头社地图作者地图更新图一塞弗尔斯克方向俄年伞兵从两侧逼近韦塞洛耶村占领了一些据点图二阿夫迪...   2024/1/3 0:07   广西
1739  以色列伞兵旅的成员伊利沙马丁是犹太教拉比雅科夫马丁的儿子他的部队在加沙地区遭到巴勒斯坦抵抗武...   2024/1/3 0:05   陕西

[1468 rows x 3 columns]

In [178]:
# 对文本进行jieba分词
import jieba
import jieba.posseg as pseg
import pickle
import os
# 词性pickle文件的保存路径
pos_filename = os.path.join('data','interim',os.path.basename(raw_data_path).split('.')[0]+'pos.pickle')
# 如果存在词性pickle文件，则直接加载
if os.path.exists(pos_filename):
    with open(pos_filename, 'rb') as f:
        data = pickle.load(f)
else: # 没有则生成
    jieba.load_userdict('data/补充词典.txt')
    data.iloc[:,0] = list(map(lambda s:list(pseg.cut(s,use_paddle=True)),data.iloc[:,0]))
    # data.iloc[:,0] = list(map(lambda s:list(jieba.cut(s,use_paddle=True)),data.iloc[:,0]))
    with open(pos_filename,'wb') as f:
        pickle.dump(data, f)
data

微博正文            发布时间   ip
0     [联合国/nt, 机构/n, 每/r, 经/n, 快讯/nz, 半岛/n, 电视台/n, 当...  2024/1/6 23:48  NaN
1     [伊朗/ns, 报纸/n, 我们/r, 将/d, 对/p, 犹太复国/nz, 主义者/n, ...  2024/1/6 23:33   贵州
2     [朝鲜/ns, 发/v, 炮弹/n, 震惊/v, 世界/n, 让/v, 美国/ns, 很/z...  2024/1/6 23:24   广东
3     [巴勒斯坦/ns, 圣城/ns, 旅/n, 发布/v, 了/ul, 一段/m, 有趣/a, ...  2024/1/1 23:57   陕西
4     [以色列/ns, 军队/n, 在/p, 约旦河西岸/ns, 杰里科/nrt, 市/n, 入口...  2024/1/6 23:16   广东
...                                                 ...             ...  ...
1735  [据/p, 报道/v, 黎巴嫩/nr, 首都/d, 贝鲁特/nr, 南郊/ns, 的/uj,...   2024/1/3 0:32   广东
1736        [教/v, 你/r, 不要/df, 重蹈覆辙/i, 你/r, 还/d, 反唇相讥/i]   2024/1/3 0:27   云南
1737  [建/v, 个/q, 话/n, 痨群/n, 更新/d, 一些/m, 不/d, 占用/v, 微...   2024/1/3 0:09   广西
1738  [箭头/n, 社/n, 地图/n, 作者/n, 地图更新/nz, 图一塞弗/nrt, 尔斯/...   2024/1/3 0:07   广西
1739  [以色列/ns, 伞兵/n, 旅/n, 的/uj, 成员/n, 伊利/nz, 沙/nr, 马...   2024/1/3 0:05   陕西

[1468 rows x 3 columns]

In [179]:
# 根据词性删除虚词
# data.drop(data[data.iloc[:,0]<10],inplace=True)
for i in range(len(data)):
    data.iloc[i,0] = list(filter(lambda x: x.flag not in ['t', 'p', 'm', 'q', 'r', 'y', 'u', 'm'], data.iloc[i,0]))
# 删除单个字的词
data.iloc[:,0] = [[word.word for word in line if len(word.word)>1]for line in data.iloc[:,0]]
backup_data = data

In [180]:
# 去掉文本中的停用词
def drop_stopwords(contents, stopwords):
    contents_clean = []
    for line in contents:
        line_clean = []
        for word in line:
            if word in stopwords:
                continue
            line_clean.append(word)
        contents_clean.append(line_clean)
    return contents_clean
stopwords = []
with open('data/停用词.txt','r',encoding='utf8') as f:
    stopwords = f.readlines()
stopwords = set(map(lambda s:s.replace('\n',''),stopwords))
stopwords
data.iloc[:,0] = drop_stopwords(data.iloc[:,0], stopwords)
# data = data[data['微博正文'].apply(lambda x: 30 < len(x) < 50)]
data = data[data['微博正文'].apply(lambda x:len(x) > 70)]
min(list(map(len, data.iloc[:,0])))

71

In [181]:
# 保存处理后数据
# 处理后数据文件名
processed_filename = f'weibo_{month}_processed'
data.to_csv(os.path.join('data','processed',processed_filename+'.csv'), encoding='utf_8_sig')
with open(os.path.join('data','processed',processed_filename+'.txt'),'w+', encoding='utf8') as f:
    f.writelines([' '.join(line)+'\n' for line in data.iloc[:,0]])

len(data)

135

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
#将文本中的词转换成词频矩阵
vectorizer = CountVectorizer()
# print(vectorizer)
corpus = [' '.join(line) for line in data.iloc[:,0]]
#计算某个词出现的次数
X = vectorizer.fit_transform(corpus)
# print(type(X),X)
#获取词袋中所有文本关键词
word = vectorizer.get_feature_names_out()
print(len(word))
#查看词频结果
print(X.toarray())
print(X.shape)

54311
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(7756, 54311)


In [40]:
import pickle
with open('data/interim/dec_doc_topic_mat.pickle','rb') as f:
    mat = pickle.load(f)
sum(list(map(lambda x:1 if len(x)<10 else 0, mat)))
# mat

144