In [164]:
import pandas as pd

In [165]:
# 原始数据路径
month = 'nov'
raw_data_path = f'data/raw/巴以冲突{month}.csv'
data = pd.read_csv(raw_data_path, encoding='utf8')
data.head()

微博正文             发布时间  ip
0  哈马斯发布来自也门的声援#巴以冲突##以色列称坚决拒绝停火##以色列轰炸后的加沙尸横遍野#L...  2023/12/1 23:57  北京
1                        #伊朗#用无人机炸了#以色列#的船#巴以冲突##中东#  2023/12/1 23:56  广东
2  在以色列军队恢复军事行动的1小时内，真主党武装在以色列北部边境确认发起了3次袭击。抵抗之弧在...  2023/12/1 23:56  广东
3  卡塔尔外交部宣布，该国对停火结束后恢复敌对行动“深感遗憾”，双方未达成延长停火协议。卡塔尔外...  2023/12/1 23:49  北京
4  卡桑旅的火箭弹在特拉维夫上空，铁穹紧急拦截#巴以冲突##以军已恢复军事打击行动#L靖难战神李...  2023/12/1 23:45  广东

In [166]:
import re
data.iloc[:,0] = list(map(lambda line: re.sub(r'L.*微博视频','',line), data.iloc[:,0]))
data.iloc[:,0] = list(map(lambda line: re.sub(r'#.*#','',line), data.iloc[:,0]))
data

微博正文             发布时间  ip
0                                           哈马斯发布来自也门的声援  2023/12/1 23:57  北京
1                                                         2023/12/1 23:56  广东
2      在以色列军队恢复军事行动的1小时内，真主党武装在以色列北部边境确认发起了3次袭击。抵抗之弧在...  2023/12/1 23:56  广东
3      卡塔尔外交部宣布，该国对停火结束后恢复敌对行动“深感遗憾”，双方未达成延长停火协议。卡塔尔外...  2023/12/1 23:49  北京
4                                  卡桑旅的火箭弹在特拉维夫上空，铁穹紧急拦截  2023/12/1 23:45  广东
...                                                  ...              ...  ..
31980  今天是2023年11月6日星期一，昨天在理发店听到理发师在于顾客聊天，能从巴以冲突聊到恒大，...  2023/11/6 20:44  新疆
31981  【外交部：外交部发言人汪文斌在今天例行记者会上表示，本轮巴以冲突已造成超过11000人死亡，...  2023/11/6 20:44  重庆
31982  基辛格：美国正在分裂！解体就在眼前基辛格表示，美国正在遭受国内分裂以及国际混乱，然而美国却没...  2023/11/6 20:43  上海
31983  为什么支持巴勒斯坦？这位英国小哥说得很对！其实全世界支持巴勒斯坦，跟反犹无关，也无关宗教。反...  2023/11/6 20:42  广东
31984           ��🇧黎巴嫩真主党武装展示其反舰导弹，以作为对以色列海岸周边美国舰队存在的回应。  2023/11/6 20:42  广东

[31985 rows x 3 columns]

In [167]:
# 只保留汉字
def is_chinese(uchar):
    if uchar >= u'\u4e00' and uchar <= u'\u9fa5':
        return True
    else:
        return False

def format_str(content):
    content_str = ''
    for i in content:
        if is_chinese(i):
            content_str = content_str + i
    return content_str

data.iloc[:,0] = list(map(format_str, data.iloc[:,0]))
data

微博正文             发布时间  ip
0                                           哈马斯发布来自也门的声援  2023/12/1 23:57  北京
1                                                         2023/12/1 23:56  广东
2      在以色列军队恢复军事行动的小时内真主党武装在以色列北部边境确认发起了次袭击抵抗之弧在临时停火...  2023/12/1 23:56  广东
3      卡塔尔外交部宣布该国对停火结束后恢复敌对行动深感遗憾双方未达成延长停火协议卡塔尔外交部称各方...  2023/12/1 23:49  北京
4                                   卡桑旅的火箭弹在特拉维夫上空铁穹紧急拦截  2023/12/1 23:45  广东
...                                                  ...              ...  ..
31980  今天是年月日星期一昨天在理发店听到理发师在于顾客聊天能从巴以冲突聊到恒大再到股市和楼市想想过...  2023/11/6 20:44  新疆
31981  外交部外交部发言人汪文斌在今天例行记者会上表示本轮巴以冲突已造成超过人死亡其中绝大多数是平民...  2023/11/6 20:44  重庆
31982  基辛格美国正在分裂解体就在眼前基辛格表示美国正在遭受国内分裂以及国际混乱然而美国却没办法凝聚...  2023/11/6 20:43  上海
31983  为什么支持巴勒斯坦这位英国小哥说得很对其实全世界支持巴勒斯坦跟反犹无关也无关宗教反对以色列只...  2023/11/6 20:42  广东
31984                黎巴嫩真主党武装展示其反舰导弹以作为对以色列海岸周边美国舰队存在的回应  2023/11/6 20:42  广东

[31985 rows x 3 columns]

In [168]:
import numpy as np

# 去重
data = data.drop_duplicates(['微博正文'],keep='first')
data = data.drop(data[data['微博正文']==''].index)
data

微博正文             发布时间  ip
0                                           哈马斯发布来自也门的声援  2023/12/1 23:57  北京
2      在以色列军队恢复军事行动的小时内真主党武装在以色列北部边境确认发起了次袭击抵抗之弧在临时停火...  2023/12/1 23:56  广东
3      卡塔尔外交部宣布该国对停火结束后恢复敌对行动深感遗憾双方未达成延长停火协议卡塔尔外交部称各方...  2023/12/1 23:49  北京
4                                   卡桑旅的火箭弹在特拉维夫上空铁穹紧急拦截  2023/12/1 23:45  广东
5                                                 这图不服不行  2023/12/1 23:41  北京
...                                                  ...              ...  ..
31979  以色列说自己出于自卫目的打击哈马斯一个月下来以色列轰炸了民居难民营医院学校教堂甚至救护车炸死...  2023/11/6 20:44  广东
31980  今天是年月日星期一昨天在理发店听到理发师在于顾客聊天能从巴以冲突聊到恒大再到股市和楼市想想过...  2023/11/6 20:44  新疆
31982  基辛格美国正在分裂解体就在眼前基辛格表示美国正在遭受国内分裂以及国际混乱然而美国却没办法凝聚...  2023/11/6 20:43  上海
31983  为什么支持巴勒斯坦这位英国小哥说得很对其实全世界支持巴勒斯坦跟反犹无关也无关宗教反对以色列只...  2023/11/6 20:42  广东
31984                黎巴嫩真主党武装展示其反舰导弹以作为对以色列海岸周边美国舰队存在的回应  2023/11/6 20:42  广东

[23148 rows x 3 columns]

In [169]:
# 对文本进行jieba分词
import jieba
import jieba.posseg as pseg
import pickle
import os
# 词性pickle文件的保存路径
pos_filename = os.path.join('data','interim',os.path.basename(raw_data_path).split('.')[0]+'pos.pickle')
# 如果存在词性pickle文件，则直接加载
if os.path.exists(pos_filename):
    with open(pos_filename, 'rb') as f:
        data = pickle.load(f)
else: # 没有则生成
    jieba.load_userdict('data/补充词典.txt')
    data.iloc[:,0] = list(map(lambda s:list(pseg.cut(s,use_paddle=True)),data.iloc[:,0]))
    # data.iloc[:,0] = list(map(lambda s:list(jieba.cut(s,use_paddle=True)),data.iloc[:,0]))
    with open(pos_filename,'wb') as f:
        pickle.dump(data, f)
data

微博正文             发布时间  ip
0                [哈马斯/nrt, 发布/v, 来自/v, 也门/d, 的/uj, 声援/n]  2023/12/1 23:57  北京
2      [在/p, 以色列/ns, 军队/n, 恢复/v, 军事行动/n, 的/uj, 小时/n, ...  2023/12/1 23:56  广东
3      [卡塔尔/nr, 外交部/nt, 宣布/v, 该国/r, 对/p, 停火/v, 结束/v, ...  2023/12/1 23:49  北京
4      [卡桑/nrt, 旅/n, 的/uj, 火箭弹/n, 在/p, 特拉维夫/nrt, 上空/v...  2023/12/1 23:45  广东
5                                 [这/r, 图/n, 不服/v, 不行/v]  2023/12/1 23:41  北京
...                                                  ...              ...  ..
31979  [以色列/ns, 说/v, 自己/r, 出于/v, 自卫/v, 目的/n, 打击/v, 哈马...  2023/11/6 20:44  广东
31980  [今天/t, 是/v, 年月日/t, 星期一/t, 昨天/t, 在/p, 理发店/n, 听到...  2023/11/6 20:44  新疆
31982  [基辛格/n, 美国/ns, 正在/t, 分裂/v, 解体/n, 就/d, 在/p, 眼前/...  2023/11/6 20:43  上海
31983  [为什么/r, 支持/v, 巴勒斯坦/ns, 这位/rz, 英国/ns, 小哥/n, 说/v...  2023/11/6 20:42  广东
31984  [黎巴嫩真主党/nt, 武装/n, 展示/v, 其/r, 反舰导弹/nz, 以/p, 作为/...  2023/11/6 20:42  广东

[23148 rows x 3 columns]

In [170]:
# 根据词性删除虚词
# data.drop(data[data.iloc[:,0]<10],inplace=True)
for i in range(len(data)):
    data.iloc[i,0] = list(filter(lambda x: x.flag not in ['t', 'p', 'm', 'q', 'r', 'y', 'u', 'm'], data.iloc[i,0]))
# 删除单个字的词
data.iloc[:,0] = [[word.word for word in line if len(word.word)>1]for line in data.iloc[:,0]]
backup_data = data

In [171]:
# 去掉文本中的停用词
def drop_stopwords(contents, stopwords):
    contents_clean = []
    for line in contents:
        line_clean = []
        for word in line:
            if word in stopwords:
                continue
            line_clean.append(word)
        contents_clean.append(line_clean)
    return contents_clean
stopwords = []
with open('data/停用词.txt','r',encoding='utf8') as f:
    stopwords = f.readlines()
stopwords = set(map(lambda s:s.replace('\n',''),stopwords))
stopwords
data.iloc[:,0] = drop_stopwords(data.iloc[:,0], stopwords)
# data = data[data['微博正文'].apply(lambda x: 30 < len(x) < 50)]
data = data[data['微博正文'].apply(lambda x:len(x) > 70)]
min(list(map(len, data.iloc[:,0])))

71

In [172]:
# 保存处理后数据
# 处理后数据文件名
processed_filename = f'weibo_{month}_processed'
data.to_csv(os.path.join('data','processed',processed_filename+'.csv'), encoding='utf_8_sig')
with open(os.path.join('data','processed',processed_filename+'.txt'),'w+', encoding='utf8') as f:
    f.writelines([' '.join(line)+'\n' for line in data.iloc[:,0]])

len(data)

3874

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
#将文本中的词转换成词频矩阵
vectorizer = CountVectorizer()
# print(vectorizer)
corpus = [' '.join(line) for line in data.iloc[:,0]]
#计算某个词出现的次数
X = vectorizer.fit_transform(corpus)
# print(type(X),X)
#获取词袋中所有文本关键词
word = vectorizer.get_feature_names_out()
print(len(word))
#查看词频结果
print(X.toarray())
print(X.shape)

54311
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(7756, 54311)


In [40]:
import pickle
with open('data/interim/dec_doc_topic_mat.pickle','rb') as f:
    mat = pickle.load(f)
sum(list(map(lambda x:1 if len(x)<10 else 0, mat)))
# mat

144